name: Build and testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    
jobs:
  build_and_test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: [18.x, 20.x, 22.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-versions}}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-versions}}
    - name: Install dependancies
      run: npm install
    - name: Start tests 
      run: npm test
  
  security_tests:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependancies
        run: npm install
      - name: Run security tests
        run: npm audit
  
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: security_tests
    steps:
      - name: Deploy to production
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait-for-success: true